task:
  matrix:
    - name: FreeBSD
      freebsd_instance:
        image_family: freebsd-13-1
    - name: Linux ARMv8
      arm_container:
        image: ubuntu:latest
  env:
    matrix:
      - JULIA_VERSION: 1.3
      - JULIA_VERSION: 1
      - JULIA_VERSION: nightly
  allow_failures: $JULIA_VERSION == 'nightly'
  install_script: |
    URL="https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh"
    set -x
    if command -v curl; then
        echo "wget"
        sh -c "$(curl ${URL})"
    elif command -v wget; then
        echo "wget"
        sh -c "$(wget ${URL} -O-)"
    elif command -v fetch; then
        sh -c "$(fetch ${URL} -o -)"
    fi
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
  coverage_script:
    - cirrusjl coverage codecov
